### PR TITLE
created an issue template

### PR DESCRIPTION
**Pull request by MikeSelva12**
I added a new file for an issue template - bug question.md

### CODE REVIEW

**Comment by nhelchitnis** [comment]
This looks great @MikeSelva12  👍🏼.

Can you remove the space in the file name and use `_`?

**Comment by MikeSelva12** [comment]
Okay Noted

**Review by nhelchitnis — APPROVED** [review]
Looks good, thank you 👍

**Comment by nhelchitnis** [comment]
@all-contributors please add @MikeSelva12 for documentation

**Pull request merged**
